server:
  port: 9098

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5


management:
  endpoint:
    healthshow-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true




spring:
  application:
    name: school-service
  main:
    allow-circular-references: true

logging:
  level:
    com.demo.training: DEBUG