server:
  port: 8761
 
eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
  server:
    waitTimeInMsWhenSyncEmpty: 0


management:
  security:
    enabled: false
spring:
  boot:
    admin:
      context-path: /admin  #A different context path for admin server has been provided not conflicting with eureka
  application:
    name: Eureka-Server
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://localhost:8888}